### ISSUE TITLE
@typescript-eslint/experimental-utils can be replaced by @typescript-eslint/utils

### ISSUE THREAD

**Issue by olegomon** [eydrian/eslint-vertical-import#1]
[This Documentation](https://www.npmjs.com/package/@typescript-eslint/experimental-utils) states that `@typescript-eslint/experimental-utils` can be replaced by the `@typescript-eslint/utils` package. As we consume this ESLint plugin, we cannot resolve the dependency of `@typescript-eslint/experimental-utils` internally. 

It would be great if this plugin would get maintenance release with updated dependencies.

**Comment by eydrian** [comment]
@olegomon can you check if it works? I updated and clean the dependencies

**Comment by eydrian** [comment]
According to @olegomon it is working as expected

**Comment by olegomon** [comment]
@eydrian many thanks for updating the dependencies. The update was flawless and worked like a charm! I'd like to buy you a coffee! ;)
